name: test-func

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

# see: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    steps:
     - name: harden runner
       uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
       with:
         egress-policy: block
         allowed-endpoints: >
           github.com:443
           api.github.com:443
           proxy.github.com:443
           proxy.golang.org:443
           raw.githubusercontent.com:443
           objects.githubusercontent.com:443
           proxy.golang.org:443
     - name: checkout code
       uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
     - name: setup go
       uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
       with:
         go-version: "1.21"
     - name: start the MySQL service
       run: sudo systemctl start mysql.service
     - name: setup PostgreSQL
       id: postgres
       uses: ikalnytskyi/action-setup-postgres@687404e7b78b0b3471751635e69f70d54a09d6e7 # v6
       with:
         username: runner
         password: runner
         port: 34837
         postgres-version: "16"
         ssl: "on"
     - name: reset test databases
       run: ./internal/testing/scripts/reset.sh
       env:
         POSTGRESQL_DSN: ${{ steps.postgres.outputs.connection-uri }}
     - name: run functional tests
       run: cd internal/testing && go test -v ./...
       env:
         POSTGRESQL_DSN: ${{ steps.postgres.outputs.connection-uri }}
